# PostgreSQL. Versions 12+ recommended.
# gem install pg
#
# Ensure the PostgreSQL gem is defined in your Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sigelbanco
  password: sigelsenha
  host: localhost
  port: 5432

development:
  <<: *default
  database: sigel_development

test:
  <<: *default
  database: sigel_test

production:
  <<: *default
  database: sigel_production
  # Recomenda-se sobrescrever via ENV em produção real:
  # username: <%= ENV["DB_USERNAME"] %>
  # password: <%= ENV["DB_PASSWORD"] %>
  # host: <%= ENV["DB_HOST"] %>
